// +build !ignore_autogenerated

/*
Copyright 2020 Critical Stack, LLC

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by conversion-gen. DO NOT EDIT.

package v1alpha1

import (
	unsafe "unsafe"

	v1alpha2 "github.com/criticalstack/cluster-api-bootstrap-provider-crit/apis/bootstrap/v1alpha2"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*CritConfig)(nil), (*v1alpha2.CritConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_CritConfig_To_v1alpha2_CritConfig(a.(*CritConfig), b.(*v1alpha2.CritConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha2.CritConfig)(nil), (*CritConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_CritConfig_To_v1alpha1_CritConfig(a.(*v1alpha2.CritConfig), b.(*CritConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*CritConfigList)(nil), (*v1alpha2.CritConfigList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_CritConfigList_To_v1alpha2_CritConfigList(a.(*CritConfigList), b.(*v1alpha2.CritConfigList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha2.CritConfigList)(nil), (*CritConfigList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_CritConfigList_To_v1alpha1_CritConfigList(a.(*v1alpha2.CritConfigList), b.(*CritConfigList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*CritConfigStatus)(nil), (*v1alpha2.CritConfigStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_CritConfigStatus_To_v1alpha2_CritConfigStatus(a.(*CritConfigStatus), b.(*v1alpha2.CritConfigStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha2.CritConfigStatus)(nil), (*CritConfigStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_CritConfigStatus_To_v1alpha1_CritConfigStatus(a.(*v1alpha2.CritConfigStatus), b.(*CritConfigStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*CritConfigTemplate)(nil), (*v1alpha2.CritConfigTemplate)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_CritConfigTemplate_To_v1alpha2_CritConfigTemplate(a.(*CritConfigTemplate), b.(*v1alpha2.CritConfigTemplate), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha2.CritConfigTemplate)(nil), (*CritConfigTemplate)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_CritConfigTemplate_To_v1alpha1_CritConfigTemplate(a.(*v1alpha2.CritConfigTemplate), b.(*CritConfigTemplate), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*CritConfigTemplateList)(nil), (*v1alpha2.CritConfigTemplateList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_CritConfigTemplateList_To_v1alpha2_CritConfigTemplateList(a.(*CritConfigTemplateList), b.(*v1alpha2.CritConfigTemplateList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha2.CritConfigTemplateList)(nil), (*CritConfigTemplateList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_CritConfigTemplateList_To_v1alpha1_CritConfigTemplateList(a.(*v1alpha2.CritConfigTemplateList), b.(*CritConfigTemplateList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*CritConfigTemplateResource)(nil), (*v1alpha2.CritConfigTemplateResource)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_CritConfigTemplateResource_To_v1alpha2_CritConfigTemplateResource(a.(*CritConfigTemplateResource), b.(*v1alpha2.CritConfigTemplateResource), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha2.CritConfigTemplateResource)(nil), (*CritConfigTemplateResource)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_CritConfigTemplateResource_To_v1alpha1_CritConfigTemplateResource(a.(*v1alpha2.CritConfigTemplateResource), b.(*CritConfigTemplateResource), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*CritConfigTemplateSpec)(nil), (*v1alpha2.CritConfigTemplateSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_CritConfigTemplateSpec_To_v1alpha2_CritConfigTemplateSpec(a.(*CritConfigTemplateSpec), b.(*v1alpha2.CritConfigTemplateSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha2.CritConfigTemplateSpec)(nil), (*CritConfigTemplateSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_CritConfigTemplateSpec_To_v1alpha1_CritConfigTemplateSpec(a.(*v1alpha2.CritConfigTemplateSpec), b.(*CritConfigTemplateSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*File)(nil), (*v1alpha2.File)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_File_To_v1alpha2_File(a.(*File), b.(*v1alpha2.File), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha2.File)(nil), (*File)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_File_To_v1alpha1_File(a.(*v1alpha2.File), b.(*File), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*NTP)(nil), (*v1alpha2.NTP)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_NTP_To_v1alpha2_NTP(a.(*NTP), b.(*v1alpha2.NTP), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha2.NTP)(nil), (*NTP)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_NTP_To_v1alpha1_NTP(a.(*v1alpha2.NTP), b.(*NTP), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*User)(nil), (*v1alpha2.User)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_User_To_v1alpha2_User(a.(*User), b.(*v1alpha2.User), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha2.User)(nil), (*User)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_User_To_v1alpha1_User(a.(*v1alpha2.User), b.(*User), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*CritConfigSpec)(nil), (*v1alpha2.CritConfigSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_CritConfigSpec_To_v1alpha2_CritConfigSpec(a.(*CritConfigSpec), b.(*v1alpha2.CritConfigSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*v1alpha2.CritConfigSpec)(nil), (*CritConfigSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_CritConfigSpec_To_v1alpha1_CritConfigSpec(a.(*v1alpha2.CritConfigSpec), b.(*CritConfigSpec), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1alpha1_CritConfig_To_v1alpha2_CritConfig(in *CritConfig, out *v1alpha2.CritConfig, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_CritConfigSpec_To_v1alpha2_CritConfigSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_CritConfigStatus_To_v1alpha2_CritConfigStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_CritConfig_To_v1alpha2_CritConfig is an autogenerated conversion function.
func Convert_v1alpha1_CritConfig_To_v1alpha2_CritConfig(in *CritConfig, out *v1alpha2.CritConfig, s conversion.Scope) error {
	return autoConvert_v1alpha1_CritConfig_To_v1alpha2_CritConfig(in, out, s)
}

func autoConvert_v1alpha2_CritConfig_To_v1alpha1_CritConfig(in *v1alpha2.CritConfig, out *CritConfig, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha2_CritConfigSpec_To_v1alpha1_CritConfigSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha2_CritConfigStatus_To_v1alpha1_CritConfigStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha2_CritConfig_To_v1alpha1_CritConfig is an autogenerated conversion function.
func Convert_v1alpha2_CritConfig_To_v1alpha1_CritConfig(in *v1alpha2.CritConfig, out *CritConfig, s conversion.Scope) error {
	return autoConvert_v1alpha2_CritConfig_To_v1alpha1_CritConfig(in, out, s)
}

func autoConvert_v1alpha1_CritConfigList_To_v1alpha2_CritConfigList(in *CritConfigList, out *v1alpha2.CritConfigList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]v1alpha2.CritConfig, len(*in))
		for i := range *in {
			if err := Convert_v1alpha1_CritConfig_To_v1alpha2_CritConfig(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

// Convert_v1alpha1_CritConfigList_To_v1alpha2_CritConfigList is an autogenerated conversion function.
func Convert_v1alpha1_CritConfigList_To_v1alpha2_CritConfigList(in *CritConfigList, out *v1alpha2.CritConfigList, s conversion.Scope) error {
	return autoConvert_v1alpha1_CritConfigList_To_v1alpha2_CritConfigList(in, out, s)
}

func autoConvert_v1alpha2_CritConfigList_To_v1alpha1_CritConfigList(in *v1alpha2.CritConfigList, out *CritConfigList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CritConfig, len(*in))
		for i := range *in {
			if err := Convert_v1alpha2_CritConfig_To_v1alpha1_CritConfig(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

// Convert_v1alpha2_CritConfigList_To_v1alpha1_CritConfigList is an autogenerated conversion function.
func Convert_v1alpha2_CritConfigList_To_v1alpha1_CritConfigList(in *v1alpha2.CritConfigList, out *CritConfigList, s conversion.Scope) error {
	return autoConvert_v1alpha2_CritConfigList_To_v1alpha1_CritConfigList(in, out, s)
}

func autoConvert_v1alpha1_CritConfigSpec_To_v1alpha2_CritConfigSpec(in *CritConfigSpec, out *v1alpha2.CritConfigSpec, s conversion.Scope) error {
	// WARNING: in.ControlPlaneConfiguration requires manual conversion: does not exist in peer-type
	// WARNING: in.WorkerConfiguration requires manual conversion: does not exist in peer-type
	out.Files = *(*[]v1alpha2.File)(unsafe.Pointer(&in.Files))
	out.PreCritCommands = *(*[]string)(unsafe.Pointer(&in.PreCritCommands))
	out.PostCritCommands = *(*[]string)(unsafe.Pointer(&in.PostCritCommands))
	out.Users = *(*[]v1alpha2.User)(unsafe.Pointer(&in.Users))
	out.NTP = (*v1alpha2.NTP)(unsafe.Pointer(in.NTP))
	out.Format = v1alpha2.Format(in.Format)
	out.Verbosity = in.Verbosity
	return nil
}

func autoConvert_v1alpha2_CritConfigSpec_To_v1alpha1_CritConfigSpec(in *v1alpha2.CritConfigSpec, out *CritConfigSpec, s conversion.Scope) error {
	// WARNING: in.Config requires manual conversion: does not exist in peer-type
	out.Files = *(*[]File)(unsafe.Pointer(&in.Files))
	out.PreCritCommands = *(*[]string)(unsafe.Pointer(&in.PreCritCommands))
	out.PostCritCommands = *(*[]string)(unsafe.Pointer(&in.PostCritCommands))
	out.Users = *(*[]User)(unsafe.Pointer(&in.Users))
	out.NTP = (*NTP)(unsafe.Pointer(in.NTP))
	out.Format = Format(in.Format)
	out.Verbosity = in.Verbosity
	return nil
}

func autoConvert_v1alpha1_CritConfigStatus_To_v1alpha2_CritConfigStatus(in *CritConfigStatus, out *v1alpha2.CritConfigStatus, s conversion.Scope) error {
	out.Ready = in.Ready
	out.DataSecretName = (*string)(unsafe.Pointer(in.DataSecretName))
	out.FailureReason = in.FailureReason
	out.FailureMessage = in.FailureMessage
	return nil
}

// Convert_v1alpha1_CritConfigStatus_To_v1alpha2_CritConfigStatus is an autogenerated conversion function.
func Convert_v1alpha1_CritConfigStatus_To_v1alpha2_CritConfigStatus(in *CritConfigStatus, out *v1alpha2.CritConfigStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_CritConfigStatus_To_v1alpha2_CritConfigStatus(in, out, s)
}

func autoConvert_v1alpha2_CritConfigStatus_To_v1alpha1_CritConfigStatus(in *v1alpha2.CritConfigStatus, out *CritConfigStatus, s conversion.Scope) error {
	out.Ready = in.Ready
	out.DataSecretName = (*string)(unsafe.Pointer(in.DataSecretName))
	out.FailureReason = in.FailureReason
	out.FailureMessage = in.FailureMessage
	return nil
}

// Convert_v1alpha2_CritConfigStatus_To_v1alpha1_CritConfigStatus is an autogenerated conversion function.
func Convert_v1alpha2_CritConfigStatus_To_v1alpha1_CritConfigStatus(in *v1alpha2.CritConfigStatus, out *CritConfigStatus, s conversion.Scope) error {
	return autoConvert_v1alpha2_CritConfigStatus_To_v1alpha1_CritConfigStatus(in, out, s)
}

func autoConvert_v1alpha1_CritConfigTemplate_To_v1alpha2_CritConfigTemplate(in *CritConfigTemplate, out *v1alpha2.CritConfigTemplate, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_CritConfigTemplateSpec_To_v1alpha2_CritConfigTemplateSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_CritConfigTemplate_To_v1alpha2_CritConfigTemplate is an autogenerated conversion function.
func Convert_v1alpha1_CritConfigTemplate_To_v1alpha2_CritConfigTemplate(in *CritConfigTemplate, out *v1alpha2.CritConfigTemplate, s conversion.Scope) error {
	return autoConvert_v1alpha1_CritConfigTemplate_To_v1alpha2_CritConfigTemplate(in, out, s)
}

func autoConvert_v1alpha2_CritConfigTemplate_To_v1alpha1_CritConfigTemplate(in *v1alpha2.CritConfigTemplate, out *CritConfigTemplate, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha2_CritConfigTemplateSpec_To_v1alpha1_CritConfigTemplateSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha2_CritConfigTemplate_To_v1alpha1_CritConfigTemplate is an autogenerated conversion function.
func Convert_v1alpha2_CritConfigTemplate_To_v1alpha1_CritConfigTemplate(in *v1alpha2.CritConfigTemplate, out *CritConfigTemplate, s conversion.Scope) error {
	return autoConvert_v1alpha2_CritConfigTemplate_To_v1alpha1_CritConfigTemplate(in, out, s)
}

func autoConvert_v1alpha1_CritConfigTemplateList_To_v1alpha2_CritConfigTemplateList(in *CritConfigTemplateList, out *v1alpha2.CritConfigTemplateList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]v1alpha2.CritConfigTemplate, len(*in))
		for i := range *in {
			if err := Convert_v1alpha1_CritConfigTemplate_To_v1alpha2_CritConfigTemplate(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

// Convert_v1alpha1_CritConfigTemplateList_To_v1alpha2_CritConfigTemplateList is an autogenerated conversion function.
func Convert_v1alpha1_CritConfigTemplateList_To_v1alpha2_CritConfigTemplateList(in *CritConfigTemplateList, out *v1alpha2.CritConfigTemplateList, s conversion.Scope) error {
	return autoConvert_v1alpha1_CritConfigTemplateList_To_v1alpha2_CritConfigTemplateList(in, out, s)
}

func autoConvert_v1alpha2_CritConfigTemplateList_To_v1alpha1_CritConfigTemplateList(in *v1alpha2.CritConfigTemplateList, out *CritConfigTemplateList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CritConfigTemplate, len(*in))
		for i := range *in {
			if err := Convert_v1alpha2_CritConfigTemplate_To_v1alpha1_CritConfigTemplate(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

// Convert_v1alpha2_CritConfigTemplateList_To_v1alpha1_CritConfigTemplateList is an autogenerated conversion function.
func Convert_v1alpha2_CritConfigTemplateList_To_v1alpha1_CritConfigTemplateList(in *v1alpha2.CritConfigTemplateList, out *CritConfigTemplateList, s conversion.Scope) error {
	return autoConvert_v1alpha2_CritConfigTemplateList_To_v1alpha1_CritConfigTemplateList(in, out, s)
}

func autoConvert_v1alpha1_CritConfigTemplateResource_To_v1alpha2_CritConfigTemplateResource(in *CritConfigTemplateResource, out *v1alpha2.CritConfigTemplateResource, s conversion.Scope) error {
	if err := Convert_v1alpha1_CritConfigSpec_To_v1alpha2_CritConfigSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_CritConfigTemplateResource_To_v1alpha2_CritConfigTemplateResource is an autogenerated conversion function.
func Convert_v1alpha1_CritConfigTemplateResource_To_v1alpha2_CritConfigTemplateResource(in *CritConfigTemplateResource, out *v1alpha2.CritConfigTemplateResource, s conversion.Scope) error {
	return autoConvert_v1alpha1_CritConfigTemplateResource_To_v1alpha2_CritConfigTemplateResource(in, out, s)
}

func autoConvert_v1alpha2_CritConfigTemplateResource_To_v1alpha1_CritConfigTemplateResource(in *v1alpha2.CritConfigTemplateResource, out *CritConfigTemplateResource, s conversion.Scope) error {
	if err := Convert_v1alpha2_CritConfigSpec_To_v1alpha1_CritConfigSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha2_CritConfigTemplateResource_To_v1alpha1_CritConfigTemplateResource is an autogenerated conversion function.
func Convert_v1alpha2_CritConfigTemplateResource_To_v1alpha1_CritConfigTemplateResource(in *v1alpha2.CritConfigTemplateResource, out *CritConfigTemplateResource, s conversion.Scope) error {
	return autoConvert_v1alpha2_CritConfigTemplateResource_To_v1alpha1_CritConfigTemplateResource(in, out, s)
}

func autoConvert_v1alpha1_CritConfigTemplateSpec_To_v1alpha2_CritConfigTemplateSpec(in *CritConfigTemplateSpec, out *v1alpha2.CritConfigTemplateSpec, s conversion.Scope) error {
	if err := Convert_v1alpha1_CritConfigTemplateResource_To_v1alpha2_CritConfigTemplateResource(&in.Template, &out.Template, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_CritConfigTemplateSpec_To_v1alpha2_CritConfigTemplateSpec is an autogenerated conversion function.
func Convert_v1alpha1_CritConfigTemplateSpec_To_v1alpha2_CritConfigTemplateSpec(in *CritConfigTemplateSpec, out *v1alpha2.CritConfigTemplateSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_CritConfigTemplateSpec_To_v1alpha2_CritConfigTemplateSpec(in, out, s)
}

func autoConvert_v1alpha2_CritConfigTemplateSpec_To_v1alpha1_CritConfigTemplateSpec(in *v1alpha2.CritConfigTemplateSpec, out *CritConfigTemplateSpec, s conversion.Scope) error {
	if err := Convert_v1alpha2_CritConfigTemplateResource_To_v1alpha1_CritConfigTemplateResource(&in.Template, &out.Template, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha2_CritConfigTemplateSpec_To_v1alpha1_CritConfigTemplateSpec is an autogenerated conversion function.
func Convert_v1alpha2_CritConfigTemplateSpec_To_v1alpha1_CritConfigTemplateSpec(in *v1alpha2.CritConfigTemplateSpec, out *CritConfigTemplateSpec, s conversion.Scope) error {
	return autoConvert_v1alpha2_CritConfigTemplateSpec_To_v1alpha1_CritConfigTemplateSpec(in, out, s)
}

func autoConvert_v1alpha1_File_To_v1alpha2_File(in *File, out *v1alpha2.File, s conversion.Scope) error {
	out.Path = in.Path
	out.Owner = in.Owner
	out.Permissions = in.Permissions
	out.Encoding = v1alpha2.Encoding(in.Encoding)
	out.Content = in.Content
	return nil
}

// Convert_v1alpha1_File_To_v1alpha2_File is an autogenerated conversion function.
func Convert_v1alpha1_File_To_v1alpha2_File(in *File, out *v1alpha2.File, s conversion.Scope) error {
	return autoConvert_v1alpha1_File_To_v1alpha2_File(in, out, s)
}

func autoConvert_v1alpha2_File_To_v1alpha1_File(in *v1alpha2.File, out *File, s conversion.Scope) error {
	out.Path = in.Path
	out.Owner = in.Owner
	out.Permissions = in.Permissions
	out.Encoding = Encoding(in.Encoding)
	out.Content = in.Content
	return nil
}

// Convert_v1alpha2_File_To_v1alpha1_File is an autogenerated conversion function.
func Convert_v1alpha2_File_To_v1alpha1_File(in *v1alpha2.File, out *File, s conversion.Scope) error {
	return autoConvert_v1alpha2_File_To_v1alpha1_File(in, out, s)
}

func autoConvert_v1alpha1_NTP_To_v1alpha2_NTP(in *NTP, out *v1alpha2.NTP, s conversion.Scope) error {
	out.Servers = *(*[]string)(unsafe.Pointer(&in.Servers))
	out.Enabled = (*bool)(unsafe.Pointer(in.Enabled))
	return nil
}

// Convert_v1alpha1_NTP_To_v1alpha2_NTP is an autogenerated conversion function.
func Convert_v1alpha1_NTP_To_v1alpha2_NTP(in *NTP, out *v1alpha2.NTP, s conversion.Scope) error {
	return autoConvert_v1alpha1_NTP_To_v1alpha2_NTP(in, out, s)
}

func autoConvert_v1alpha2_NTP_To_v1alpha1_NTP(in *v1alpha2.NTP, out *NTP, s conversion.Scope) error {
	out.Servers = *(*[]string)(unsafe.Pointer(&in.Servers))
	out.Enabled = (*bool)(unsafe.Pointer(in.Enabled))
	return nil
}

// Convert_v1alpha2_NTP_To_v1alpha1_NTP is an autogenerated conversion function.
func Convert_v1alpha2_NTP_To_v1alpha1_NTP(in *v1alpha2.NTP, out *NTP, s conversion.Scope) error {
	return autoConvert_v1alpha2_NTP_To_v1alpha1_NTP(in, out, s)
}

func autoConvert_v1alpha1_User_To_v1alpha2_User(in *User, out *v1alpha2.User, s conversion.Scope) error {
	out.Name = in.Name
	out.Gecos = (*string)(unsafe.Pointer(in.Gecos))
	out.Groups = (*string)(unsafe.Pointer(in.Groups))
	out.HomeDir = (*string)(unsafe.Pointer(in.HomeDir))
	out.Inactive = (*bool)(unsafe.Pointer(in.Inactive))
	out.Shell = (*string)(unsafe.Pointer(in.Shell))
	out.Passwd = (*string)(unsafe.Pointer(in.Passwd))
	out.PrimaryGroup = (*string)(unsafe.Pointer(in.PrimaryGroup))
	out.LockPassword = (*bool)(unsafe.Pointer(in.LockPassword))
	out.Sudo = (*string)(unsafe.Pointer(in.Sudo))
	out.SSHAuthorizedKeys = *(*[]string)(unsafe.Pointer(&in.SSHAuthorizedKeys))
	return nil
}

// Convert_v1alpha1_User_To_v1alpha2_User is an autogenerated conversion function.
func Convert_v1alpha1_User_To_v1alpha2_User(in *User, out *v1alpha2.User, s conversion.Scope) error {
	return autoConvert_v1alpha1_User_To_v1alpha2_User(in, out, s)
}

func autoConvert_v1alpha2_User_To_v1alpha1_User(in *v1alpha2.User, out *User, s conversion.Scope) error {
	out.Name = in.Name
	out.Gecos = (*string)(unsafe.Pointer(in.Gecos))
	out.Groups = (*string)(unsafe.Pointer(in.Groups))
	out.HomeDir = (*string)(unsafe.Pointer(in.HomeDir))
	out.Inactive = (*bool)(unsafe.Pointer(in.Inactive))
	out.Shell = (*string)(unsafe.Pointer(in.Shell))
	out.Passwd = (*string)(unsafe.Pointer(in.Passwd))
	out.PrimaryGroup = (*string)(unsafe.Pointer(in.PrimaryGroup))
	out.LockPassword = (*bool)(unsafe.Pointer(in.LockPassword))
	out.Sudo = (*string)(unsafe.Pointer(in.Sudo))
	out.SSHAuthorizedKeys = *(*[]string)(unsafe.Pointer(&in.SSHAuthorizedKeys))
	return nil
}

// Convert_v1alpha2_User_To_v1alpha1_User is an autogenerated conversion function.
func Convert_v1alpha2_User_To_v1alpha1_User(in *v1alpha2.User, out *User, s conversion.Scope) error {
	return autoConvert_v1alpha2_User_To_v1alpha1_User(in, out, s)
}
